spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url : ${MYSQL_URL}
  #    username: ${MYSQL_NAME}
  #    password: ${MYSQL_PASSWORD}
  #  jpa:
  #    defer-datasource-initialization: true
  #    properties:
  #      hibernate:
  #        format_sql: 'true'
  #        dialect: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: 'true'
  #        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/withEat
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
  servlet:
    multipart:      # 이미지 관련 설정
      maxFileSize: 2MB # 파일 하나의 최대 크기
      maxRequestSize: 6MB  # 한 번에 최대 업로드 가능 용량

jwt:
  issuer: tmdgh784@naver.com
  secret_key: arom-backend

cloud:
  aws:
    credentials:
      accessKey: sss
      secretKey: sss
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: discipline24test1
    stack:
      auto: false
